### ISSUE TITLE
登录页表单

### ISSUE THREAD

**Issue by neo1218** [Muxi-Studio/muxi_site#39]
登录页表单前后端合并时，后端不知道样式名称。
![2016-01-12 9 48 09](https://cloud.githubusercontent.com/assets/10671733/12252385/b33975be-b911-11e5-9997-5efc217d6991.png)

**Comment by neo1218** [comment]
@zxc0328 抽个空把名字给我。我来合并。

**Comment by zxc0328** [comment]
上面的input我用的元素选择器所以样式已经ok了。按钮的class是.btn_login
