### ISSUE TITLE
木犀分享在Safari上显示有问题

### ISSUE THREAD

**Issue by neo1218** [Muxi-Studio/muxi_site#40]
![2016-01-12 9 50 07](https://cloud.githubusercontent.com/assets/10671733/12252399/e74b89d2-b911-11e5-9c69-759a502d92ed.png)

**Comment by neo1218** [comment]
@zxc0328  这个你来搞

**Comment by zxc0328** [comment]
OK，你具体说一下哪个页面呗

**Comment by neo1218** [comment]
@zxc0328  就是这个页面呀
木犀分享首页

**Comment by zxc0328** [comment]
搞好了，字体文件貌似一定要远程的才可以用。我直接用了google的cdn，貌似没有被墙，至少校园网可以访问这个。七牛上我不是标准用户没法传字体文件。
