### ISSUE TITLE
木犀博客归档页

### ISSUE THREAD

**Issue by neo1218** [Muxi-Studio/muxi_site#42]
![2016-01-12 10 48 32](https://cloud.githubusercontent.com/assets/10671733/12253368/3522eda0-b91a-11e5-904d-20a070eb334c.png)

**Comment by neo1218** [comment]
@zxc0328 你来分配

**Comment by neo1218** [comment]
已告诉
@sunliying

**Comment by zxc0328** [comment]
先做成一个基本的列表吧，就是左右边栏保留，然后中间是义工标题列表。老王这几天在做官网首页，过几天再设计样式

**Comment by neo1218** [comment]
@sunliying

**Comment by zxc0328** [comment]
fixed in this [commit](https://github.com/Muxi-Studio/muxi_site/commit/831c33511da3a1f4ab6815135c465dc0dc605cd3)
