### ISSUE TITLE
个人信息修改页要不要加上返回按钮

### ISSUE THREAD

**Issue by neo1218** [Muxi-Studio/muxi_site#68]
![2016-02-01 12 17 30](https://cloud.githubusercontent.com/assets/10671733/12708745/35f886d0-c8de-11e5-89f2-614e7249d0f3.png)

现在只有一个确定

**Comment by zxc0328** [comment]
可以啊 @lyz-stephen

**Comment by lyz-stephen** [comment]
我觉得加上好一点 @neo1218

**Comment by lyz-stephen** [comment]
我之前是询问了一下梁小怡的，不过她说她看过的一些网站很多都没有的，因为是直接打开一个新页面，所以点击确定后直接关闭就好了

**Comment by neo1218** [comment]
这样也可以，github的个人页也没有返回，那就不加了吧
@zxc0328 @lyz-stephen  你们觉得呢？

**Comment by zxc0328** [comment]
我觉得要加

**Comment by zxc0328** [comment]
@lyz-stephen 你加一个吧

**Comment by neo1218** [comment]
@zxc0328 要不要和梁小怡说。。。

**Comment by zxc0328** [comment]
@neo1218 不用了。
