### ISSUE TITLE
Code Review 0208 CSS的两个问题

### ISSUE THREAD

**Issue by zxc0328** [Muxi-Studio/muxi_site#73]
@sunliying 
### 两栏布局问题

我发现你在两栏的时候很喜欢用这样的布局，左边的设置`float`，又边的什么也不设。比如主页博客列表里面
图片：
````
.middle_box .blog .conte .des img {
    height: 40px;
    width: 40px;
    float: left;
    position: relative;
}
````
标题：
````
.middle_box .blog .conte .title {
    padding: 0 10px;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}
````

左边设置了浮动之后，就脱离文档流，但是因为还是一个实体，所以右边的内容还是从图片开始排的。
这样的确达到了你的效果。然而如何你查看元素，就会发现右边的标题溢出了。因为左边是脱离文档流的，所以右边的标题的宽度自然是100%，你设置了一个`overflow: hidden`之后触发了BFC，然后用起来和两个都设置浮动是一样一样的。

然而这样真的好吗？这个布局本来不是这么用的。
这个布局的用途是，左边浮动，右边自适应。右边设置和左边宽度一样的`margin-left`。这样右边的`content box`的宽度就是`100%-(margin-left)`。

你要么就用两个浮动，显式设置宽度。如果偷懒右边不想设置宽度，那就用`float+margin-left`的，没问题。你现在这种布局，`overflow: hidden`没有浮动的包裹性，所以右边的实际宽度依然是`100%`。你设置了各种` white-space: nowrap; text-overflow: ellipsis;`这样的属性让文字不溢出，所以看起来是没有问题的。然而右边标题的宽度实际上依然是溢出的。虽然效果ok，但是从代码上来说这个是没法接受的。

### 缺少wrapper元素

这段markup
````
<p class="title">
    <a href="/blog/post/1">DOM API详解（一）</a>
</p>
<span class="name">neo1218</span>
<span class="date">2016-02-05 07:22</span>
````

**你在逗我吗**？inline级别的`span`就直接和block级别的`p`一起用了？

从布局的层级关系分明的角度上来说，你应该加一个块级wrapper元素，这样我们才看的清楚元素之间的层级。

````
<p class="title">
    <a href="/blog/post/1">DOM API详解（一）</a>
</p>
<div class="info">
   <span class="name">neo1218</span>
   <span class="date">2016-02-05 07:22</span>
</div>
````
你加一个`div.info`，结构上就很清楚了，不然`span`和标题是同一个级别的？？

从表现上来讲，你这样当然是没有问题的，因为有匿名`line block`。但是`HTML`的作用就是给出一个合理的层级结构的`markup`。

还有，你这边的两个`span`，我想调整一下`line-height`，怎么办？我没有wrapper元素我就只能用`span`来控制了。这就写了多余的代码了。控制的细粒度也太细。

**Comment by zxc0328** [comment]
结果你还真这么设置了` line-height`。

你有没有发现要这么调` line-height`来上下移动会很奇怪？因为你的`span`的` line-height`是相对于`.des`这个`div`的。

````
.name,
.date {
    color: $article_gray;
    line-height: 23px;
    font-size: 12px;
    padding: 0px 10px;
}
````

我现在把`line-height`设置成和字号一样，也就是说`span`的`height`就是字体的高度。然后用`div.info`的`margin-top`来控制文本的垂直布局，这样不是更清晰吗？

**Comment by sunliying** [comment]
两栏布局我知道了，内联元素和块级元素不放在一块写，但是下面的line-height可以设置为父层框的高度与前面的img高度相同，使字体垂直居中，这样还好吧～～

**Comment by zxc0328** [comment]
你用`line-height`当然可以达到目的。这个随意。我比较偏好像素级别的控制。用`margin-top`更容易一些。

关键不是内联元素和块级元素不放在一块写，关键是`HTML`的层级问题
