### ISSUE TITLE
个人介绍问题

### ISSUE THREAD

**Issue by kasheemlew** [Muxi-Studio/muxi_site#89]
<img width="434" alt="2016-04-08 16 07 09" src="https://cloud.githubusercontent.com/assets/14333766/14377737/efbb6f0c-fda3-11e5-8b65-e1c5855a5352.png">

编辑应从左上角开始

**Comment by kasheemlew** [comment]
@zxc0328

**Comment by misakar** [comment]
解决了的问题就可以close了。

**Comment by misakar** [comment]
@kasheemlew

**Comment by zxc0328** [comment]
还没解决。另外个人页的js要重写 @stephenLYao

**Comment by stephenLYZ** [comment]
ok
