### ISSUE TITLE
博客需要加一个[简介]字段

### ISSUE THREAD

**Issue by misakar** [Muxi-Studio/muxi_site#95]
![2016-05-29 10 01 01](https://cloud.githubusercontent.com/assets/10671733/15633816/e47e1b22-25e8-11e6-8bb2-7dbc2edb3a5a.png)
简介是博客概括，放在博客卡片空白的地方。

**Comment by tsonglew** [comment]
已加 @stephenLYao 运行之前先迁移一下数据库~

**Comment by misakar** [comment]
![tt](https://cloud.githubusercontent.com/assets/10671733/15634152/dd041494-25ef-11e6-9ddf-86cef27728e0.gif)

**Comment by misakar** [comment]
其实前端可以没必要迁移数据库, 因为前端一般不会去修改数据库结构，前端需要的是数据，也就是保持数据库连接即可，不需要保持数据库版本。

**Comment by tsonglew** [comment]
没这个字段跑不了额。。
